# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(605, 440)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:rgb(43, 209, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(90, 320, 110, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startBtn.sizePolicy().hasHeightForWidth())
        self.startBtn.setSizePolicy(sizePolicy)
        self.startBtn.setStyleSheet("color:rgb(0, 0, 0); font: 75 10pt \"MS Shell Dlg 2\";\n"
"font: 10pt \"Times New Roman\";")
        self.startBtn.setIconSize(QtCore.QSize(16, 16))
        self.startBtn.setObjectName("startBtn")
        self.endBtn = QtWidgets.QPushButton(self.centralwidget)
        self.endBtn.setGeometry(QtCore.QRect(200, 320, 110, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endBtn.sizePolicy().hasHeightForWidth())
        self.endBtn.setSizePolicy(sizePolicy)
        self.endBtn.setStyleSheet("color:rgb(0, 0, 0); font: 75 10pt \"MS Shell Dlg 2\"; \n"
"font: 10pt \"Times New Roman\";")
        self.endBtn.setObjectName("endBtn")
        self.gesturesBtn = QtWidgets.QPushButton(self.centralwidget)
        self.gesturesBtn.setGeometry(QtCore.QRect(310, 320, 110, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gesturesBtn.sizePolicy().hasHeightForWidth())
        self.gesturesBtn.setSizePolicy(sizePolicy)
        self.gesturesBtn.setStyleSheet("color:rgb(0, 0, 0); font: 75 10pt \"MS Shell Dlg 2\"; \n"
"font: 10pt \"Times New Roman\";")
        self.gesturesBtn.setObjectName("gesturesBtn")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(420, 320, 110, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitBtn.sizePolicy().hasHeightForWidth())
        self.exitBtn.setSizePolicy(sizePolicy)
        self.exitBtn.setStyleSheet("color:; font: 75 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0); \n"
"font: 10pt \"Times New Roman\";")
        self.exitBtn.setObjectName("exitBtn")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(170, 70, 331, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Niagara Engraved")
        font.setPointSize(58)
        font.setBold(False)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 60, 151, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Resources/handpoint.png"))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "All Hands - Main Menu"))
        self.startBtn.setText(_translate("MainWindow", "START"))
        self.endBtn.setText(_translate("MainWindow", "END"))
        self.gesturesBtn.setText(_translate("MainWindow", "CONTROLS"))
        self.exitBtn.setText(_translate("MainWindow", "EXIT"))
        self.labelTitle.setText(_translate("MainWindow", "All Hands"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
