# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'part3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(1200, 934)
        Options.setStyleSheet("background-color:rgb(43, 209, 255)\n"
"\n"
"")
        self.mouseImg = QtWidgets.QLabel(Options)
        self.mouseImg.setGeometry(QtCore.QRect(60, 130, 231, 201))
        self.mouseImg.setText("")
        self.mouseImg.setPixmap(QtGui.QPixmap("../resources/move-mouse.png"))
        self.mouseImg.setObjectName("mouseImg")
        self.left_clickImg = QtWidgets.QLabel(Options)
        self.left_clickImg.setGeometry(QtCore.QRect(350, 150, 231, 181))
        self.left_clickImg.setText("")
        self.left_clickImg.setPixmap(QtGui.QPixmap("../resources/left-click.png"))
        self.left_clickImg.setObjectName("left_clickImg")
        self.right_clickImg = QtWidgets.QLabel(Options)
        self.right_clickImg.setGeometry(QtCore.QRect(660, 90, 211, 251))
        self.right_clickImg.setText("")
        self.right_clickImg.setPixmap(QtGui.QPixmap("../resources/right-click.png"))
        self.right_clickImg.setObjectName("right_clickImg")
        self.drkb_Img = QtWidgets.QLabel(Options)
        self.drkb_Img.setGeometry(QtCore.QRect(370, 490, 221, 291))
        self.drkb_Img.setText("")
        self.drkb_Img.setPixmap(QtGui.QPixmap("../resources/keyboard.png"))
        self.drkb_Img.setObjectName("drkb_Img")
        self.mouseText = QtWidgets.QTextBrowser(Options)
        self.mouseText.setGeometry(QtCore.QRect(30, 360, 291, 91))
        self.mouseText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mouseText.setLineWidth(15)
        self.mouseText.setObjectName("mouseText")
        self.leftclickText = QtWidgets.QTextBrowser(Options)
        self.leftclickText.setGeometry(QtCore.QRect(330, 360, 291, 91))
        self.leftclickText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftclickText.setLineWidth(15)
        self.leftclickText.setObjectName("leftclickText")
        self.rightclickText = QtWidgets.QTextBrowser(Options)
        self.rightclickText.setGeometry(QtCore.QRect(630, 360, 291, 91))
        self.rightclickText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightclickText.setLineWidth(15)
        self.rightclickText.setObjectName("rightclickText")
        self.dragText = QtWidgets.QTextBrowser(Options)
        self.dragText.setGeometry(QtCore.QRect(930, 360, 261, 91))
        self.dragText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dragText.setLineWidth(15)
        self.dragText.setObjectName("dragText")
        self.doubleclickText = QtWidgets.QTextBrowser(Options)
        self.doubleclickText.setGeometry(QtCore.QRect(30, 800, 291, 91))
        self.doubleclickText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.doubleclickText.setLineWidth(15)
        self.doubleclickText.setObjectName("doubleclickText")
        self.drkbText = QtWidgets.QTextBrowser(Options)
        self.drkbText.setGeometry(QtCore.QRect(330, 800, 301, 91))
        self.drkbText.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drkbText.setLineWidth(15)
        self.drkbText.setObjectName("drkbText")
        self.infoText = QtWidgets.QTextBrowser(Options)
        self.infoText.setGeometry(QtCore.QRect(10, 10, 541, 71))
        self.infoText.setStyleSheet("")
        self.infoText.setObjectName("infoText")
        self.drkbText_2 = QtWidgets.QTextBrowser(Options)
        self.drkbText_2.setGeometry(QtCore.QRect(770, 800, 301, 91))
        self.drkbText_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drkbText_2.setLineWidth(15)
        self.drkbText_2.setObjectName("drkbText_2")
        self.drag = QtWidgets.QLabel(Options)
        self.drag.setGeometry(QtCore.QRect(960, 60, 211, 281))
        self.drag.setText("")
        self.drag.setPixmap(QtGui.QPixmap("../resources/drag.png"))
        self.drag.setObjectName("drag")
        self.dclick = QtWidgets.QLabel(Options)
        self.dclick.setGeometry(QtCore.QRect(60, 490, 211, 301))
        self.dclick.setText("")
        self.dclick.setPixmap(QtGui.QPixmap("../resources/double-click.png"))
        self.dclick.setObjectName("dclick")
        self.left_clickImg.raise_()
        self.right_clickImg.raise_()
        self.drkb_Img.raise_()
        self.mouseText.raise_()
        self.leftclickText.raise_()
        self.rightclickText.raise_()
        self.dragText.raise_()
        self.doubleclickText.raise_()
        self.drkbText.raise_()
        self.infoText.raise_()
        self.drkbText_2.raise_()
        self.drag.raise_()
        self.dclick.raise_()
        self.mouseImg.raise_()

        self.retranslateUi(Options)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", "All Hands - Controls"))
        self.mouseText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE 1: MOVE MOUSE </span></p></body></html>"))
        self.leftclickText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE 2: LEFT CLICK</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\"><br /></p></body></html>"))
        self.rightclickText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE 3: RIGHT CLICK</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\"><br /></p></body></html>"))
        self.dragText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE 4: DRAG</span></p></body></html>"))
        self.doubleclickText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE 5: DOUBLE CLICK</span></p></body></html>"))
        self.drkbText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE 6: DISPLAY/REMOVE KB</span></p></body></html>"))
        self.infoText.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:13pt; font-weight:600; color:#000000;\">- Once the Start button is pressed, Hit the Backspace key on your </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:13pt; font-weight:600; color:#000000;\">   keyboard to start the gesture recognition and Spacebar key to stop</span></p></body></html>"))
        self.drkbText_2.setHtml(_translate("Options", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\">GESTURE X: TBD</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; color:#000000;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Options = QtWidgets.QWidget()
    ui = Ui_Options()
    ui.setupUi(Options)
    Options.show()
    sys.exit(app.exec_())
